cc_library(
    name = 'cmdline',
    hdrs = ['cmdline.h'],
    strip_include_prefix = '.',
    linkstatic = True,
    visibility = ['//visibility:public'],
)

cc_library(
    name = 'terminal',
    hdrs = ['terminal.h'],
    strip_include_prefix = '.',
    linkstatic = True,
    visibility = ['//visibility:public'],
)

